spring:
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: admin
      database: ipCheck
      port: 27017
      host: localhost

integration:
  telegram:
    url: https://api.telegram.org
    token: secret

